import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Preston Lund Portfolio",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
    //   className="bg-white dark:bg-black text-black dark:text-white"
      lang="en"
    >
      <body>
        {children}
      </body>
    </html>
  );
}
