import "../globals.css";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Preston Lund Portfolio",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className="bg-white dark:bg-black text-black dark:text-white"
      lang="en"
    >
      <body className='max-w-3xl mx-auto py-10'>
        <header>
          <Link href='/' className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">Preston</Link>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
